### ISSUE TITLE
Convert php object Card into js object

### ISSUE THREAD

**Issue by AzaeI** [MagicTheGathering/mtg-sdk-php#6] opened 2017-08-30 11:10 UTC
I'm getting Card object in php .
When i use `json_encode` on the card object, i got an empty object.

**Comment by guiwoda** [comment] 2017-08-30 13:33
This could be fixed by implementing `JsonSerialize` on the `Card` object, but I'd put the method implementation on the `DataBag` trait so that other objects can also easily serialize to json.

Want to give it a shot?

**Comment by AzaeI** [comment] 2017-08-30 14:10
Yeah sure.
if `Set` can be serialize to json too, it'll be nice

**Comment by guiwoda** [comment] 2017-08-30 14:13
Both `Card` and `Set` use `DataBag`, so it could be implemented in both!

**Comment by AzaeI** [comment] 2017-08-30 14:18
I don't really understand exactly how it works , 
I'm just a beginner using your api ;)
Thanks for responding that fast btw.
It'll take sometime to fix it ?

**Comment by guiwoda** [comment] 2017-08-30 14:31
Take your time to understand the project and how it works right now, then make a pull request with your changes.
Open source work is done by the community, so if you need something, you do your best to contribute it yourself. What you ask for is not a bugfix, so I don't have any urgency of implementing it myself, but I'd be glad to accept your PR.

Hope you can pull it off! I'm sure you'll learn something along the way ;-)

**Comment by AzaeI** [comment] 2017-08-30 14:44
Well, i'll try :-)

**Closed as completed** 2020-04-24 07:38 UTC
